version: "3.8"
services:
  api:
    build: .
    image: cleanbooks-prod-server
    restart: always
    ports:
      - '53103:53103'
    volumes:
      - cleanbooks-prod-server:/app
    working_dir: /app
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mariadb://api-mariadb:3306/cleanbooks?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
      - SPRING_DATASOURCE_USERNAME=cleanbooks
      - SPRING_DATASOURCE_PASSWORD=leehj12!$
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        delay: 10s
        failure_action: rollback
    # knuh-db container가 생성된 후에 생성등록 및 네트워크 연결
    depends_on:
      - api-mariadb
  
  api-mariadb:
    image: mariadb
    restart: always
    ports:
      - '3336:3306'
    environment:
      MARIADB_ROOT_PASSWORD: leehj124!$leehj124!$leehj124!$
      MARIADB_DATABASE: cleanbooks
      MARIADB_USER: cleanbooks
      MARIADB_PASSWORD: leehj12!$

volumes:
  cleanbooks-prod-server:
